export const topics = [
	"Blue",
	"On the Lake",
	"WallPapers",
	"3D Renders",
	"Nature",
	"Text & Patterns",
	"Architecture & Interiors",
	"Film",
	"Street Photography",
	"Experimental",
	"Animals",
	"Fashion & Beauty",
	"Business & Work",
	"Food & Drink",
	"Travel",
	"People",
	"Spirituality",
	"Athletics",
	"Health & Wellness",
	"Current Events",
	"Arts & Culture",
];
